name: walmart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - awscli
  - black
  - coverage
  - dash=0.37.0
  - fbprophet
  - flake8
  - gcc
  - gunicorn
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - plotnine
  - pytest
  - python-dotenv>=0.5.1
  - Sphinx
  - seaborn
  - statsmodels
  - tox
  - pip:
    - -e .
