name: walmart
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.6
  - autopep8
  - awscli
  - black
  - coverage
  - dash
  - dash-renderer
  - dash-html-components
  - dash-core-components
  - flake8
  - gunicorn
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - plotly
  - pytest
  - python-dotenv>=0.5.1
  - Sphinx
  - seaborn
  - statsmodels
  - tox
  - pip:
    - -e .
